// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UrlCutterClient is the client API for UrlCutter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlCutterClient interface {
	Create(ctx context.Context, in *OldUrl, opts ...grpc.CallOption) (*CutUrl, error)
}

type urlCutterClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlCutterClient(cc grpc.ClientConnInterface) UrlCutterClient {
	return &urlCutterClient{cc}
}

func (c *urlCutterClient) Create(ctx context.Context, in *OldUrl, opts ...grpc.CallOption) (*CutUrl, error) {
	out := new(CutUrl)
	err := c.cc.Invoke(ctx, "/api.Url_cutter/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlCutterServer is the server API for UrlCutter service.
// All implementations must embed UnimplementedUrlCutterServer
// for forward compatibility
type UrlCutterServer interface {
	Create(context.Context, *OldUrl) (*CutUrl, error)
	mustEmbedUnimplementedUrlCutterServer()
}

// UnimplementedUrlCutterServer must be embedded to have forward compatible implementations.
type UnimplementedUrlCutterServer struct {
}

func (UnimplementedUrlCutterServer) Create(context.Context, *OldUrl) (*CutUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUrlCutterServer) mustEmbedUnimplementedUrlCutterServer() {}

// UnsafeUrlCutterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlCutterServer will
// result in compilation errors.
type UnsafeUrlCutterServer interface {
	mustEmbedUnimplementedUrlCutterServer()
}

func RegisterUrlCutterServer(s grpc.ServiceRegistrar, srv UrlCutterServer) {
	s.RegisterService(&UrlCutter_ServiceDesc, srv)
}

func _UrlCutter_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OldUrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlCutterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Url_cutter/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlCutterServer).Create(ctx, req.(*OldUrl))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlCutter_ServiceDesc is the grpc.ServiceDesc for UrlCutter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlCutter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Url_cutter",
	HandlerType: (*UrlCutterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UrlCutter_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcserver.proto",
}
